version: "3.7"
services:
  react:
    container_name: spades-app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/src
      - /src/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true
